// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using JSONDataModelCocktail;
//
//    var cocktailDataModel = CocktailDataModel.FromJson(jsonString);

namespace JSONDataModelCocktail
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CocktailDataModel
    {
        [JsonProperty("drinks")]
        public List<Drink> Drinks { get; set; }
    }

    public partial class Drink
    {
        [JsonProperty("strDrink")]
        public string StrDrink { get; set; }

        [JsonProperty("strDrinkThumb")]
        public Uri StrDrinkThumb { get; set; }

        [JsonProperty("idDrink")]
        public long IdDrink { get; set; }
    }

    public partial class CocktailDataModel
    {
        public static CocktailDataModel FromJson(string json) => JsonConvert.DeserializeObject<CocktailDataModel>(json, JSONDataModelCocktail.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this CocktailDataModel self) => JsonConvert.SerializeObject(self, JSONDataModelCocktail.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
